# This is the Ansible Galaxy requirements file to pull in the correct roles

- src: https://git.ecicd.dso.ncps.us-cert.gov/dso-pipeline/openshift-applier.git
  scm: git
  version: v2.1.1
  name: openshift-applier

- src: https://git.ecicd.dso.ncps.us-cert.gov/dso-pipeline/ansible-role-openshift_cluster_login.git
  scm: git
  version: v1.0
  name: openshift_cluster_login
